export const lightTheme = {
    background: "#fff",
    color: "#121212",
    accentColor: "#3D84C6",
    aboutColor: "#ff7e67", // Example color
    educationColor: "#ffc764",
    experiencesColor: "#64b5f6",
    projectsColor: "#9575cd",
    skillsColor: "#4db6ac",
    chronoTheme: {
        cardBgColor: "white",
        cardForeColor: "black",
        titleColor: "white",
    },
    timelineLineColor: "#ccc",
    cardBackground: "#fff",
    cardFooterBackground: "#f7f7f7",
    cardBorderColor: "#00000020",
    navbarTheme: {
        linkColor: "#dedede",
        linkHoverColor: "#fefefe",
        linkActiveColor: "#fefefe",
    },
    bsPrimaryVariant: "light",
    bsSecondaryVariant: "dark",
    socialIconBgColor: "#121212",
};

export const darkTheme = {
    background: "#464646",
    color: "#eee",
    accentColor: "#3D84C6",
    aboutColor: "#e64a19",
    educationColor: "#ffa000",
    experiencesColor: "#1976d2",
    projectsColor: "#7e57c2",
    skillsColor: "#00897b",
    chronoTheme: {
        cardBgColor: "#1B1B1B",
        cardForeColor: "#eee",
        titleColor: "black",
    },
    timelineLineColor: "#444",
    cardBackground: "#060606",
    cardFooterBackground: "#181818",
    cardBorderColor: "#ffffff20",
    navbarTheme: {
        linkColor: "#dedede",
        linkHoverColor: "#fefefe",
        linkActiveColor: "#fefefe",
    },
    bsPrimaryVariant: "dark",
    bsSecondaryVariant: "light",
    socialIconBgColor: "#fefefe",
};
